// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file history.proto (package skytrack.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from '@bufbuild/protobuf/codegenv2';
import { enumDesc, fileDesc, messageDesc } from '@bufbuild/protobuf/codegenv2';
import type { Message } from '@bufbuild/protobuf';

/**
 * Describes the file history.proto.
 */
export const file_history: GenFile =
	/*@__PURE__*/
	fileDesc(
		'Cg1oaXN0b3J5LnByb3RvEgtza3l0cmFjay52MSKIAQoLSGlzdG9yeUZpbGUSDwoHdmVyc2lvbhgBIAEoDRIfCgRraW5kGAIgASgOMhEuc2t5dHJhY2sudjEuS2luZBIfCgR0aWVyGAMgASgOMhEuc2t5dHJhY2sudjEuVGllchImCgVpdGVtcxgEIAMoCzIXLnNreXRyYWNrLnYxLkl0ZW1TZXJpZXMiZwoKSXRlbVNlcmllcxIKCgJpZBgBIAEoCRIQCgh0c19kZWx0YRgCIAMoEhIVCg1wcmljZV9hX2RlbHRhGAMgAygSEhUKDXByaWNlX2JfZGVsdGEYBCADKBISDQoFY291bnQYBSADKBIqQAoES2luZBIUChBLSU5EX1VOU1BFQ0lGSUVEEAASDwoLS0lORF9CQVpBQVIQARIRCg1LSU5EX0FVQ1RJT05TEAIqSwoEVGllchIUChBUSUVSX1VOU1BFQ0lGSUVEEAASDAoIVElFUl9SQVcQARIPCgtUSUVSX0hPVVJMWRACEg4KClRJRVJfREFJTFkQA2IGcHJvdG8z'
	);

/**
 * @generated from message skytrack.v1.HistoryFile
 */
export type HistoryFile = Message<'skytrack.v1.HistoryFile'> & {
	/**
	 * @generated from field: uint32 version = 1;
	 */
	version: number;

	/**
	 * @generated from field: skytrack.v1.Kind kind = 2;
	 */
	kind: Kind;

	/**
	 * @generated from field: skytrack.v1.Tier tier = 3;
	 */
	tier: Tier;

	/**
	 * @generated from field: repeated skytrack.v1.ItemSeries items = 4;
	 */
	items: ItemSeries[];
};

/**
 * Describes the message skytrack.v1.HistoryFile.
 * Use `create(HistoryFileSchema)` to create a new message.
 */
export const HistoryFileSchema: GenMessage<HistoryFile> =
	/*@__PURE__*/
	messageDesc(file_history, 0);

/**
 * Columnar, delta-encoded. Prices are round(coins * 10) so one decimal
 * survives integer encoding; deltas are vs the previous point (the first
 * delta is vs 0).
 *
 * @generated from message skytrack.v1.ItemSeries
 */
export type ItemSeries = Message<'skytrack.v1.ItemSeries'> & {
	/**
	 * @generated from field: string id = 1;
	 */
	id: string;

	/**
	 * @generated from field: repeated sint64 ts_delta = 2;
	 */
	tsDelta: bigint[];

	/**
	 * bazaar instabuy / auction lowest BIN
	 *
	 * @generated from field: repeated sint64 price_a_delta = 3;
	 */
	priceADelta: bigint[];

	/**
	 * bazaar instasell / auction median BIN
	 *
	 * @generated from field: repeated sint64 price_b_delta = 4;
	 */
	priceBDelta: bigint[];

	/**
	 * auctions only: active listings (absolute)
	 *
	 * @generated from field: repeated sint64 count = 5;
	 */
	count: bigint[];
};

/**
 * Describes the message skytrack.v1.ItemSeries.
 * Use `create(ItemSeriesSchema)` to create a new message.
 */
export const ItemSeriesSchema: GenMessage<ItemSeries> = /*@__PURE__*/ messageDesc(file_history, 1);

/**
 * @generated from enum skytrack.v1.Kind
 */
export enum Kind {
	/**
	 * @generated from enum value: KIND_UNSPECIFIED = 0;
	 */
	UNSPECIFIED = 0,

	/**
	 * @generated from enum value: KIND_BAZAAR = 1;
	 */
	BAZAAR = 1,

	/**
	 * @generated from enum value: KIND_AUCTIONS = 2;
	 */
	AUCTIONS = 2
}

/**
 * Describes the enum skytrack.v1.Kind.
 */
export const KindSchema: GenEnum<Kind> = /*@__PURE__*/ enumDesc(file_history, 0);

/**
 * @generated from enum skytrack.v1.Tier
 */
export enum Tier {
	/**
	 * @generated from enum value: TIER_UNSPECIFIED = 0;
	 */
	UNSPECIFIED = 0,

	/**
	 * @generated from enum value: TIER_RAW = 1;
	 */
	RAW = 1,

	/**
	 * @generated from enum value: TIER_HOURLY = 2;
	 */
	HOURLY = 2,

	/**
	 * @generated from enum value: TIER_DAILY = 3;
	 */
	DAILY = 3
}

/**
 * Describes the enum skytrack.v1.Tier.
 */
export const TierSchema: GenEnum<Tier> = /*@__PURE__*/ enumDesc(file_history, 1);
