// The SvelteKit app worker is generated by adapter-cloudflare at build time
// (see .svelte-kit/cloudflare/_worker.js) and has no declaration file of its
// own. Declare it so `worker/index.ts` can import it under moduleResolution
// "bundler" without allowJs.
declare module '*.svelte-kit/cloudflare/_worker.js' {
	const handler: ExportedHandler;
	export default handler;
}
