// One Worker serves both halves: the SvelteKit app (fetch) and the data
// pipeline (scheduled). The app worker is generated by adapter-cloudflare
// at build time, so `bun run build` must run before deploy (CI already does).
import app from '../.svelte-kit/cloudflare/_worker.js';
import { handleScheduled, type Env } from '../workers/pipeline/src/index';

export default { ...app, scheduled: handleScheduled } satisfies ExportedHandler<Env>;
